# config/routes.yaml

# 1. We remove/comment the automatic controller discovery
# controllers:
#     resource: routing.controllers

# 2. We leave ONLY the master PHP manifest as the source of truth
app_routes:
    resource: routes/routes.php  
    type: php